-- V1: Initial Schema
-- 此腳本包含專案初始所需的所有資料表結構

-- 1. 使用者個人檔案表 (核心表)
CREATE TABLE IF NOT EXISTS user_profiles (
    firebase_uid VARCHAR(128) PRIMARY KEY,
    birth_date DATE,
    gender VARCHAR(10),
    current_age INT,
    life_expectancy INT,
    marriage_year INT,
    career_insurance_type VARCHAR(50),
    biography TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. 使用者職涯資料表
CREATE TABLE IF NOT EXISTS user_careers (
    firebase_uid VARCHAR(128) PRIMARY KEY REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    industry VARCHAR(100),
    company_name VARCHAR(100),
    job_title VARCHAR(100),
    is_working BOOLEAN,
    monthly_salary INT,
    annual_bonus_months DECIMAL(4, 2),
    avg_working_hours_per_day DECIMAL(4, 2),
    retirement_age INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. 使用者勞工保險資料表
CREATE TABLE IF NOT EXISTS user_labor_insurances (
    firebase_uid VARCHAR(128) PRIMARY KEY REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    insurance_type VARCHAR(50),
    start_date DATE,
    avg_insured_salary_60_months INT,
    seniority_at_retirement INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. 使用者勞工退休金 (新制) 資料表
CREATE TABLE IF NOT EXISTS user_labor_pensions (
    firebase_uid VARCHAR(128) PRIMARY KEY REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    personal_contribution_rate DECIMAL(5, 4),
    employer_contribution_rate DECIMAL(5, 4),
    total_contribution_years INT,
    avg_annual_return_rate DECIMAL(5, 4),
    current_balance INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. 使用者稅務資料表
CREATE TABLE IF NOT EXISTS user_taxes (
    firebase_uid VARCHAR(128) PRIMARY KEY REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    tax_bracket_rate DECIMAL(5, 4),
    tax_deduction_amount INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. 使用者退休生活設定表
CREATE TABLE IF NOT EXISTS user_retirements (
    firebase_uid VARCHAR(128) PRIMARY KEY REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    go_go_start_age INT,
    go_go_living_cost INT,
    go_go_housing_cost INT,
    go_go_other_cost INT,
    slow_go_start_age INT,
    slow_go_living_cost_ratio DECIMAL(5, 4),
    defense_tier_code VARCHAR(50),
    no_go_start_age INT,
    ltc_care_mode VARCHAR(50),
    ltc_monthly_cost INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. 使用者副業與創業項目表
CREATE TABLE IF NOT EXISTS user_businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    start_date DATE,
    initial_investment DECIMAL(19, 2),
    income_mode VARCHAR(50),
    monthly_revenue DECIMAL(19, 2),
    monthly_expense DECIMAL(19, 2),
    tax_category VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 8. 使用者信用卡表
CREATE TABLE IF NOT EXISTS user_credit_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    card_name VARCHAR(100),
    card_type VARCHAR(50),
    credit_limit DECIMAL(19, 2),
    cash_advance_limit DECIMAL(19, 2),
    annual_fee DECIMAL(10, 2),
    interest_rate DECIMAL(5, 4),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 9. 使用者投資組合表
CREATE TABLE IF NOT EXISTS user_portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    country_code VARCHAR(10),
    currency VARCHAR(10),
    exchange_rate DECIMAL(18, 8),
    market_value DECIMAL(19, 2),
    unrealized_pnl DECIMAL(19, 2),
    realized_pnl DECIMAL(19, 2),
    cost_basis DECIMAL(19, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 10. 使用者房地產資產表
CREATE TABLE IF NOT EXISTS user_real_estates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL REFERENCES user_profiles(firebase_uid) ON DELETE CASCADE,
    address VARCHAR(255),
    city VARCHAR(100),
    country VARCHAR(100),
    property_type VARCHAR(50),
    purchase_price DECIMAL(19, 2),
    purchase_date DATE,
    market_value DECIMAL(19, 2),
    mortgage_balance DECIMAL(19, 2),
    rental_income DECIMAL(19, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
